## provide the name of the namespace
namespace:
  name: sandbox

 
service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

## define the image to execute with the Deployment 
image:
  repository:
     manu1987/techtrends 
  tag: latest
  imagePullPolicy: IfNotPresent

## set the number of replicas for an application 
replicaCount: 1

resources:
  requests:
    cpu: "250m"
    memory: "64Mi"
  limits:
    cpu: "500m"
    memory: "128Mi"

ports:
  containerPort: 3111
  protocol: TCP

livenessProbe:
  path: /healthz
  port: 3111
readinessProbe:
  path: /healthz
  port: 3111